### ISSUE TITLE
Next.js App Router Standalone Example

### ISSUE THREAD

**Issue by ADNolan** [newrelic/newrelic-node-examples#307]
## Is your feature request related to a problem? 
The existing Next.js App Router (v14) example works well in development mode and the standard Next.js production mode. When it comes to using the `standalone` output mode, there is seemingly a need for an extra step to ensure that `newrelic` node package is included in the build output node_modules.

## Feature Description
Add an example or documentation for having Newrelic work with the App router in standalone output (i.e. for running in Docker).

## Describe Alternatives
The current approach that seems to work is by adding the `instrumentation.{js|ts}` file and having a import for the `newrelic` module. Also to set the experimental instrumentation flag in the next config. The other steps outlined in the existing example for the Next.js app router configuration is needed as well.

```ts
export async function register(): Promise<void> {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('newrelic')
  }
}
```

## Additional context
- None

## Priority
**Nice to Have**

**Comment by mrickard** [comment]
Thank you for surfacing this, @ADNolan! Would you be willing to submit a PR here for it?

**Comment by ADNolan** [comment]
> Thank you for surfacing this, [@ADNolan](https://github.com/ADNolan)! Would you be willing to submit a PR here for it?

Yes, I can try to get one ready in the next day or so.

**Comment by accedo-robcc** [comment]
@ADNolan I’ve been trying the same thing without success, `newrelic.agent.collector.isConnected()` never returns `true` so the app doesn’t load when running `CMD ["node", "-r", "newrelic", "server.js"]`. 

I added `instrumentationHook: true` to `next.config.js` but the issue persist. Would you happen to have an example of the complete setup?

**Comment by ADNolan** [comment]
@accedo-robcc hey, sorry I haven't got the example up yet. Things I have noticed is that when rebuilding the docker image, try with `--no-cache` to avoid docker build cache using old code.

The quick outline is to follow the steps in the existing app router example, add the instrumentation file in the manner in the first post in this issue, and enable it in the next config with `experimental.instrumentationHook: true`.

Dockerfile command i have is the same that you put `CMD ["node", "-r", "newrelic", "server.js"]`.

Not sure it matters, but I have tried on Next.js version 14.2.16 and 14.2.23. I haven't updated to 15 yet, but that will be in the near future I believe. I will try to get the example submitted tomorrow when I will have a bit of free time.

**Comment by FDiskas** [comment]
What is the status? I also would like to see the clear example of proper integration on standalone typescript version. Thank you

**Comment by FinnIckler** [comment]
Since updating from 14 to 15 this doesn't seem to work anymore?
I have
1. The `serverExternalPackages: ["newrelic"]` in my next config 
2. Webpack rewrites with
```
webpack: (config, { isServer }) => {
    if (isServer && process.env.NODE_ENV === "production") {
      nrExternals(config);
    }
    return config;
  }
```
3. An instrumentation.ts like the one listed in the initial post

This definitely used to work at one point, but now when I start the server I get the error

```
{"v":0,"level":50,"name":"newrelic","hostname":"ip-172-31-23-175.us-west-2.compute.internal","pid":1,"time":"2025-12-17T12:52:26.836Z","msg":"New Relic for Node.js was unable to bootstrap itself due to an error:","code":"MODULE_NOT_FOUND","path":"/app/node_modules/newrelic/package.json","stack":"Error: Cannot find module '/app/node_modules/newrelic/lib/util/is-string.js'\n at createEsmNotFoundErr (node:internal/modules/cjs/loader:1458:15)\n at finalizeEsmResolution (node:internal/modules/cjs/loader:1447:9)\n at Module._resolveFilename (node:internal/modules/cjs/loader:1381:16)\n at defaultResolveImpl (node:internal/modules/cjs/loader:1059:19)\n at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1064:22)\n at Module._load (node:internal/modules/cjs/loader:1227:37)\n at TracingChannel.traceSync (node:diagnostics_channel:328:14)\n at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)\n at Module.require (node:internal/modules/cjs/loader:1504:12)\n at require (node:internal/modules/helpers:152:16)","message":"Cannot find module '/app/node_modules/newrelic/lib/util/is-string.js'"}
```

I checked the folder and I actually can not find the `is-string.js` when running
`ls node_modules/newrelic/lib/`

so nextjs does not seem to bundle these libraries anymore. I have thought about just copying the node_modules/newrelic folder as part of the docker setup, but I would like to solve this on the node level if possible

**Comment by ADNolan** [comment]
Sorry all, I haven't had time to contribute to an example. Here is what I have been using and seems to work in 15.x.

`instrumentation.ts`

```ts filename="src/instrumentation.ts"
/**
 * @docs https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation
 */
export async function register(): Promise<void> {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('newrelic');
  }
}
```

This file is separated out for in my project organizational purposes. Applied in the next config file.


```ts filename="src/config/newrelic.ts"
import type {NextConfig} from 'next';
import type {NextJsWebpackConfig} from 'next/dist/server/config-shared.js';
import nrExternals from 'newrelic/load-externals.js';

export default function usingNewRelic(nextConfig: NextConfig): NextConfig {
  nextConfig.serverExternalPackages?.push('newrelic');
  // Help prevent overriding application webpack rules
  const applicationWebPack = nextConfig.webpack;
  return {
    ...nextConfig,
    webpack: (config, context): NextJsWebpackConfig => {
      nrExternals(applicationWebPack ? applicationWebPack(config, context) : config, context);
      return config;
    },
  };
}
```

Depending on what version of Next.js 15 that is used, might have to set the `experimental.instrumentationHook: true` in the NextConfig. For NewRelic configuration, I opted to use Env vars opposed to a config file. So I am not sure if there are caveats for using a `newrelic.js` file.

#### Docker
When running in docker, the base image I used was Alpine and had a command like

* `CMD ["node", "-r", "newrelic", "server.js"]`

**Comment by FinnIckler** [comment]
Well the only difference between mine and your setup is the `nrExternals(applicationWebPack ? applicationWebPack(config, context) : config, context)`. Otherwise I am using an docker-entrypoint with `NODE_OPTIONS='-r newrelic'` and `exec node server.js` but that looks equivalent.

What is the applicationWebPack about?

**Comment by ADNolan** [comment]
> Well the only difference between mine and your setup is the `nrExternals(applicationWebPack ? applicationWebPack(config, context) : config, context)`. Otherwise I am using an docker-entrypoint with `NODE_OPTIONS='-r newrelic'` and `exec node server.js` but that looks equivalent.
> 
> What is the applicationWebPack about?

The project I have is a template for apps that has various configuration options for thing like using newrelic or not. There was an issue with the application specific webpack config getting overrode when applying newrelic. It might not be applicable to other apps depending on how its structured for generating the next config.

Project that I have working uses `"newrelic": "12.10.0"`

**Comment by FinnIckler** [comment]
I'm running 13.8. can you try to see if it still works when updating?

**Comment by amychisholm03** [comment]
Hi, thank you for filing an issue. We've significantly reworked the `nextjs-app-router` example to use the New Relic hybrid agent (OpenTelemetry bridge) as the recommended instrumentation path for Next.js. The updated example requires **Next.js >= 16** and **newrelic >= 14.1.0**.

Because of this, we won't be adding Next.js 14/15-specific guidance to `nextjs-app-router`. If you're still on Next.js 14 or 15, the [`nextjs-legacy`](https://github.com/newrelic/newrelic-node-examples/tree/main/nextjs/nextjs-legacy) example is the best reference for now. If you're able to upgrade to Next.js 16+, we'd encourage giving the updated `nextjs-app-router` example a try and opening a new issue if you hit any gaps around standalone/Docker support there.

Closing this as no longer applicable given the direction change.
